name: SLOMO
favicon: null
layout_spectrum: 0.23179
typography_spectrum: 0.19935
title: A Very Slow Mo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F2ACAC'
    - '#F4FBF3'
    - '#030302'
    - '#ACA287'
    - '#656565'
  brandStrength: 0.3125
  lightness: 0.6989247
  saturation: 0.75
  rhythmicContrast: 0.01286707
purpose: []
