name: SLOMO
favicon: null
layout_spectrum: 0.23179
typography_spectrum: 0.19935
title: A Very Slow Mo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21242b'
    - '#e4e2e5'
    - '#4c8666'
    - '#65b497'
    - '#9fcba8'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.75
  rhythmicContrast: 0.012867068406194448
purpose: []
